package version

// Version information
// This file is auto-generated by scripts/update_version.sh
// Do not edit manually - edit VERSION file instead

VERSION :: "0.14.0"
VERSION_MAJOR :: 0
VERSION_MINOR :: 14
VERSION_PATCH :: 0

// Returns the current version string
get_version :: proc() -> string {
	return VERSION
}

// Returns the full version info with build metadata
get_version_info :: proc() -> string {
	return "hound v" + VERSION
}
