version: '3'

tasks:
  build:
    desc: Build the hound binary
    cmds:
      - mkdir -p bin
      - odin build src -out:bin/hound -o:speed

  debug:
    desc: Build with debug symbols
    cmds:
      - mkdir -p bin
      - odin build src -out:bin/hound_debug -debug

  run:
    desc: 'Build and run with arguments (usage: task run -- aura)'
    cmds:
      - task: default
      - ./bin/hound {{.CLI_ARGS}}

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf bin

  install:
    desc: Install to /usr/local/bin
    cmds:
      - task: default
      - sudo cp bin/hound /usr/local/bin/
      - sudo chmod +x /usr/local/bin/hound

  test:
    desc: Run all unit tests
    cmds:
      - odin test tests -all-packages

  test:verbose:
    desc: Run tests with verbose output
    cmds:
      - odin test tests -all-packages -verbose

  test:decoder:
    desc: Run raydium decoder tests only
    cmds:
      - odin test tests -file:tests/raydium_decoder_test.odin

  test:price:
    desc: Run price fetcher tests only
    cmds:
      - odin test tests -file:tests/price_fetcher_test.odin

  test:config:
    desc: Run config tests only
    cmds:
      - odin test tests -file:tests/token_config_test.odin

  test:integration:
    desc: Run integration tests only
    cmds:
      - odin test tests -file:tests/integration_test.odin

  test:watch:
    desc: Run tests in watch mode (requires entr)
    cmds:
      - find tests src -name "*.odin" | entr -c task test
