version: '3'

tasks:
  default:
    desc: Build the hound binary
    cmds:
      - mkdir -p bin
      - odin build src -out:bin/hound -o:speed

  debug:
    desc: Build with debug symbols
    cmds:
      - mkdir -p bin
      - odin build src -out:bin/hound_debug -debug

  run:
    desc: 'Build and run with arguments (usage: task run -- aura)'
    cmds:
      - task: default
      - ./bin/hound {{.CLI_ARGS}}

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf bin

  install:
    desc: Install to /usr/local/bin
    cmds:
      - task: default
      - sudo cp bin/hound /usr/local/bin/
      - sudo chmod +x /usr/local/bin/hound
