version: '3'

tasks:
  build:
    desc: Build the hound binary
    cmds:
      - mkdir -p bin
      - odin build src -out:bin/hound -o:speed

  debug:
    desc: Build with debug symbols
    cmds:
      - mkdir -p bin
      - odin build src -out:bin/hound_debug -debug

  run:
    desc: 'Build and run with arguments (usage: task run -- aura)'
    cmds:
      - task: default
      - ./bin/hound {{.CLI_ARGS}}

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf bin

  install:
    desc: Install to /usr/local/bin
    cmds:
      - task: default
      - sudo cp bin/hound /usr/local/bin/
      - sudo chmod +x /usr/local/bin/hound

  test:
    desc: Run all unit tests
    cmds:
      - odin test tests -all-packages

  test:verbose:
    desc: Run tests with verbose output
    cmds:
      - odin test tests -all-packages -verbose

  test:decoder:
    desc: Run raydium decoder tests only
    cmds:
      - odin test tests -file:tests/raydium_decoder_test.odin

  test:price:
    desc: Run price fetcher tests only
    cmds:
      - odin test tests -file:tests/price_fetcher_test.odin

  test:config:
    desc: Run config tests only
    cmds:
      - odin test tests -file:tests/token_config_test.odin

  test:integration:
    desc: Run integration tests only
    cmds:
      - odin test tests -file:tests/integration_test.odin

  test:watch:
    desc: Run tests in watch mode (requires entr)
    cmds:
      - find tests src -name "*.odin" | entr -c task test

  menubar:example:
    desc: Build minimal menu bar example
    cmds:
      - mkdir -p bin
      - odin build src/menubar -out:bin/hound-menubar-example -o:speed -extra-linker-flags:"-framework AppKit -framework Foundation"

  menubar:example:run:
    desc: Build and run minimal menu bar example immediately
    cmds:
      - task: menubar:example
      - ./bin/hound-menubar-example

  menubar:
    desc: Build full menu bar app (when implemented)
    cmds:
      - mkdir -p bin
      - odin build src/menubar -out:bin/hound-menubar -o:speed -extra-linker-flags:"-framework AppKit -framework Foundation"

  menubar:debug:
    desc: Build menu bar app with debug symbols
    cmds:
      - mkdir -p bin
      - odin build src/menubar -out:bin/hound-menubar-debug -debug -extra-linker-flags:"-framework AppKit -framework Foundation"

  menubar:install:
    desc: Install menu bar app to /usr/local/bin
    cmds:
      - task: menubar
      - sudo cp bin/hound-menubar /usr/local/bin/
      - sudo chmod +x /usr/local/bin/hound-menubar

  version:
    desc: Display current version
    cmds:
      - cat VERSION

  version:update:
    desc: 'Update version (usage: task version:update -- 0.5.0)'
    cmds:
      - ./scripts/update_version.sh {{.CLI_ARGS}}

  version:sync:
    desc: Sync version.odin with VERSION file (regenerate version.odin)
    cmds:
      - ./scripts/update_version.sh

  version:tag:
    desc: 'Update version and create git tag (usage: task version:tag -- 0.5.0)'
    cmds:
      - ./scripts/update_version.sh {{.CLI_ARGS}} --tag

  hooks:install:
    desc: Install git hooks (pre-commit for auto-syncing version.odin)
    cmds:
      - ./scripts/install-hooks.sh
