#!/usr/bin/env ruby
# Script to update version information
# Usage: ruby scripts/update_version.rb [new_version] [--tag]
# If new_version is provided, updates VERSION file, otherwise reads existing VERSION

require 'pathname'

def get_project_root
  script_dir = Pathname.new(__FILE__).dirname
  script_dir.parent
end

def validate_semver(version)
  version.match?(/^\d+\.\d+\.\d+$/)
end

def parse_version(version)
  match = version.match(/^(\d+)\.(\d+)\.(\d+)$/)
  return nil unless match

  {
    major: match[1].to_i,
    minor: match[2].to_i,
    patch: match[3].to_i,
    full: version
  }
end

def tag_exists?(tag)
  system("git rev-parse #{tag} > /dev/null 2>&1")
end

def create_git_tag(version)
  tag = "v#{version}"

  if tag_exists?(tag)
    puts "⚠ Tag #{tag} already exists"
    return false
  end

  if system("git tag -a #{tag} -m 'Release #{tag}'")
    puts "✓ Created git tag: #{tag}"
    puts "  To push: git push origin #{tag}"
    true
  else
    warn "Error creating tag"
    false
  end
end

def generate_version_odin(version_file_path, version_info)
  content = <<~ODIN
    package version

    // Version information
    // This file is auto-generated by scripts/update_version.rb
    // Do not edit manually - edit VERSION file instead

    VERSION :: "#{version_info[:full]}"
    VERSION_MAJOR :: #{version_info[:major]}
    VERSION_MINOR :: #{version_info[:minor]}
    VERSION_PATCH :: #{version_info[:patch]}

    // Returns the current version string
    get_version :: proc() -> string {
    \treturn VERSION
    }

    // Returns the full version info with build metadata
    get_version_info :: proc() -> string {
    \treturn "hound v" + VERSION
    }
  ODIN

  File.write(version_file_path, content)
end

def main
  project_root = get_project_root
  version_file = project_root / 'VERSION'
  version_odin = project_root / 'src' / 'version' / 'version.odin'

  # Parse command line arguments
  new_version = ARGV[0] unless ARGV[0] == '--tag'
  should_tag = ARGV.include?('--tag')

  # If a new version is provided, update VERSION file
  if new_version
    unless validate_semver(new_version)
      warn 'Error: Version must be in semver format (e.g., 0.4.2)'
      exit 1
    end

    File.write(version_file, "#{new_version}\n")
    puts "✓ Updated VERSION to #{new_version}"
  end

  # Read current version
  unless version_file.exist?
    warn "Error: VERSION file not found at #{version_file}"
    exit 1
  end

  version = File.read(version_file).strip
  version_info = parse_version(version)

  unless version_info
    warn "Error: Invalid version format in VERSION file: #{version}"
    exit 1
  end

  # Generate version.odin
  generate_version_odin(version_odin, version_info)
  puts '✓ Generated src/version/version.odin'
  puts "  Version: #{version_info[:full]} " \
       "(major=#{version_info[:major]}, " \
       "minor=#{version_info[:minor]}, " \
       "patch=#{version_info[:patch]})"

  # Optional: Create git tag if --tag flag is provided
  create_git_tag(version_info[:full]) if should_tag
end

# Run main with error handling
begin
  main
rescue StandardError => e
  warn "Error: #{e.message}"
  exit 1
end
