#!/bin/bash
# Script to update version information
# Usage: ./scripts/update_version.sh [new_version]
# If new_version is provided, updates VERSION file, otherwise reads existing VERSION

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
VERSION_FILE="$PROJECT_ROOT/VERSION"
VERSION_ODIN="$PROJECT_ROOT/src/version.odin"

# If a new version is provided, update VERSION file
if [ -n "$1" ]; then
    NEW_VERSION="$1"

    # Validate semver format (basic check)
    if ! [[ "$NEW_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        echo "Error: Version must be in semver format (e.g., 0.4.2)"
        exit 1
    fi

    echo "$NEW_VERSION" > "$VERSION_FILE"
    echo "✓ Updated VERSION to $NEW_VERSION"
fi

# Read current version
if [ ! -f "$VERSION_FILE" ]; then
    echo "Error: VERSION file not found at $VERSION_FILE"
    exit 1
fi

VERSION=$(cat "$VERSION_FILE" | tr -d '[:space:]')

# Parse version components
IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

# Validate components
if [ -z "$MAJOR" ] || [ -z "$MINOR" ] || [ -z "$PATCH" ]; then
    echo "Error: Invalid version format in VERSION file: $VERSION"
    exit 1
fi

# Generate version.odin
cat > "$VERSION_ODIN" << EOF
package main

// Version information
// This file is auto-generated by scripts/update_version.sh
// Do not edit manually - edit VERSION file instead

VERSION :: "$VERSION"
VERSION_MAJOR :: $MAJOR
VERSION_MINOR :: $MINOR
VERSION_PATCH :: $PATCH

// Returns the current version string
get_version :: proc() -> string {
	return VERSION
}

// Returns the full version info with build metadata
get_version_info :: proc() -> string {
	return "hound v" + VERSION
}
EOF

echo "✓ Generated src/version.odin"
echo "  Version: $VERSION (major=$MAJOR, minor=$MINOR, patch=$PATCH)"

# Optional: Create git tag if --tag flag is provided
if [ "$2" = "--tag" ]; then
    TAG="v$VERSION"
    if git rev-parse "$TAG" >/dev/null 2>&1; then
        echo "⚠ Tag $TAG already exists"
    else
        git tag -a "$TAG" -m "Release $TAG"
        echo "✓ Created git tag: $TAG"
        echo "  To push: git push origin $TAG"
    fi
fi
