#!/usr/bin/env ruby
# Script to update version information
# Usage: ruby scripts/update_version.rb [major|minor|patch]
# Bumps the version based on semver and creates git tag

require 'pathname'

def get_project_root
  script_dir = Pathname.new(__FILE__).dirname
  script_dir.parent
end

def validate_semver(version)
  version.match?(/^\d+\.\d+\.\d+$/)
end

def parse_version(version)
  match = version.match(/^(\d+)\.(\d+)\.(\d+)$/)
  return nil unless match

  {
    major: match[1].to_i,
    minor: match[2].to_i,
    patch: match[3].to_i,
    full: version
  }
end

def bump_version(version_info, bump_type)
  case bump_type
  when 'major'
    { major: version_info[:major] + 1, minor: 0, patch: 0 }
  when 'minor'
    { major: version_info[:major], minor: version_info[:minor] + 1, patch: 0 }
  when 'patch'
    { major: version_info[:major], minor: version_info[:minor], patch: version_info[:patch] + 1 }
  else
    nil
  end
end

def format_version(version_info)
  "#{version_info[:major]}.#{version_info[:minor]}.#{version_info[:patch]}"
end

def tag_exists?(tag)
  system("git rev-parse #{tag} > /dev/null 2>&1")
end

def create_git_tag(version)
  tag = "v#{version}"

  if tag_exists?(tag)
    puts "⚠ Tag #{tag} already exists"
    return false
  end

  if system("git tag -a #{tag} -m 'Release #{tag}'")
    puts "✓ Created git tag: #{tag}"
    puts "  To push: git push origin #{tag}"
    true
  else
    warn "Error creating tag"
    false
  end
end

def generate_version_odin_content(version_info)
  <<~ODIN
    package version

    // Version information
    // This file is auto-generated by scripts/update_version.rb
    // Do not edit manually - edit VERSION file instead

    VERSION :: "#{version_info[:full]}"
    VERSION_MAJOR :: #{version_info[:major]}
    VERSION_MINOR :: #{version_info[:minor]}
    VERSION_PATCH :: #{version_info[:patch]}

    // Returns the current version string
    get_version :: proc() -> string {
    \treturn VERSION
    }

    // Returns the full version info with build metadata
    get_version_info :: proc() -> string {
    \treturn "hound v" + VERSION
    }
  ODIN
end

def needs_update?(file_path, expected_content)
  return true unless file_path.exist?
  File.read(file_path) != expected_content
end

def main
  project_root = get_project_root
  version_file = project_root / 'VERSION'
  version_odin = project_root / 'src' / 'version' / 'version.odin'

  # Parse command line arguments
  bump_type = ARGV[0]

  unless bump_type && %w[major minor patch].include?(bump_type)
    warn "Usage: ruby scripts/update_version.rb [major|minor|patch]"
    warn "  major - bump major version (X.0.0)"
    warn "  minor - bump minor version (0.X.0)"
    warn "  patch - bump patch version (0.0.X)"
    exit 1
  end

  # Read current version
  unless version_file.exist?
    warn "Error: VERSION file not found at #{version_file}"
    exit 1
  end

  current_version = File.read(version_file).strip
  current_info = parse_version(current_version)

  unless current_info
    warn "Error: Invalid version format in VERSION file: #{current_version}"
    exit 1
  end

  # Bump version
  new_info = bump_version(current_info, bump_type)
  new_version = format_version(new_info)
  new_info[:full] = new_version

  puts "Bumping #{bump_type}: #{current_version} → #{new_version}"

  # Update VERSION file if needed
  new_version_content = "#{new_version}\n"
  if needs_update?(version_file, new_version_content)
    File.write(version_file, new_version_content)
    puts "✓ Updated VERSION file"
  else
    puts "○ VERSION file already up to date"
  end

  # Generate version.odin if needed
  new_odin_content = generate_version_odin_content(new_info)
  if needs_update?(version_odin, new_odin_content)
    File.write(version_odin, new_odin_content)
    puts "✓ Updated src/version/version.odin"
  else
    puts "○ version.odin already up to date"
  end

  puts "  Version: #{new_version} " \
       "(major=#{new_info[:major]}, " \
       "minor=#{new_info[:minor]}, " \
       "patch=#{new_info[:patch]})"

  # Create git tag
  create_git_tag(new_version)
end

# Run main with error handling
begin
  main
rescue StandardError => e
  warn "Error: #{e.message}"
  exit 1
end
